# -*- coding: utf-8 -*-
"""DL-HCL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-A_p38k-agLoWRKEQKHbk7KcGr-zqZES
"""

# from google.colab import drive
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout

# drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/dataset.csv")

print(df.head())

le_category = LabelEncoder()
le_customer = LabelEncoder()

df['category'] = le_category.fit_transform(df['category'])
df['customer'] = le_customer.fit_transform(df['customer'])

scaler = MinMaxScaler()
df['amount'] = scaler.fit_transform(df[['amount']])

df = df.sort_values(by=['customer', 'step'])

import numpy as np

SEQUENCE_LENGTH = 20

def create_sequences_fast(df, seq_length):
    X, y = [], []


    grouped = df.groupby('customer')

    for _, group in grouped:
        group = group.sort_values('step')

        data = group[['amount', 'category']].values
        labels = group['fraud'].values

        # Sliding window
        for i in range(len(group) - seq_length):
            X.append(data[i:i+seq_length])
            y.append(labels[i+seq_length])

    return np.array(X), np.array(y)

X, y = create_sequences_fast(df, SEQUENCE_LENGTH)

print(X.shape, y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights = dict(enumerate(class_weights))

lstm_model = Sequential([
    LSTM(64, input_shape=(SEQUENCE_LENGTH, X.shape[2]), return_sequences=False),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

lstm_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

lstm_model.summary()

gru_model = Sequential([
    GRU(64, input_shape=(SEQUENCE_LENGTH, X.shape[2])),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

gru_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_lstm = lstm_model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2,
    class_weight=class_weights
)

history_gru = gru_model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2,
    class_weight=class_weights
)

y_pred_lstm = (lstm_model.predict(X_test) > 0.5).astype(int)
y_pred_gru = (gru_model.predict(X_test) > 0.5).astype(int)


print("LSTM Report:")
print(classification_report(y_test, y_pred_lstm))

print("GRU Report:")
print(classification_report(y_test, y_pred_gru))


print("LSTM ROC-AUC:", roc_auc_score(y_test, y_pred_lstm))
print("GRU ROC-AUC:", roc_auc_score(y_test, y_pred_gru))

from sklearn.metrics import accuracy_score

# Predict probabilities
y_prob_lstm = lstm_model.predict(X_test)

# Convert to 0/1
y_pred_lstm = (y_prob_lstm > 0.3).astype(int)

# Accuracy
lstm_acc = accuracy_score(y_test, y_pred_lstm)

print("LSTM Accuracy:", lstm_acc)

# Predict probabilities
y_prob_gru = gru_model.predict(X_test)

# Convert to 0/1
y_pred_gru = (y_prob_gru > 0.3).astype(int)

# Accuracy
gru_acc = accuracy_score(y_test, y_pred_gru)

print("GRU Accuracy:", gru_acc)

print("\nModel Comparison")
print("LSTM Accuracy:", lstm_acc)
print("GRU Accuracy:", gru_acc)

def predict_transaction(model, recent_transactions):
    recent_transactions = np.array(recent_transactions)
    recent_transactions = recent_transactions.reshape(1, SEQUENCE_LENGTH, -1)

    prob = model.predict(recent_transactions)[0][0]

    return prob

# !pip install keras-tuner

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout
from sklearn.metrics import accuracy_score

def create_lstm(units, dropout, lr):
    model = Sequential([
        LSTM(units, input_shape=(X.shape[1], X.shape[2])),
        Dropout(dropout),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=lr),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

def create_gru(units, dropout, lr):
    model = Sequential([
        GRU(units, input_shape=(X.shape[1], X.shape[2])),
        Dropout(dropout),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=lr),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

best_lstm_acc = 0
best_lstm_params = {}

# small dataset
X_small = X_train[:10000]
y_small = y_train[:10000]

for units in [32, 64]:
    for dropout in [0.2]:
        for lr in [0.001]:

            print(f"Testing: units={units}")

            model = create_lstm(units, dropout, lr)

            history = model.fit(
                X_small, y_small,
                epochs=1,
                batch_size=64,
                validation_split=0.2,
                verbose=0
            )

            val_acc = max(history.history['val_accuracy'])

            if val_acc > best_lstm_acc:
                best_lstm_acc = val_acc
                best_lstm_params = {
                    'units': units,
                    'dropout': dropout,
                    'lr': lr
                }

print("Best LSTM Params:", best_lstm_params)

model = create_lstm(**best_lstm_params)

model.fit(X_train, y_train, epochs=5, batch_size=64)

best_gru_acc = 0
best_gru_params = {}


X_small = X_train[:10000]
y_small = y_train[:10000]

for units in [32, 64]:
    for dropout in [0.2]:
        for lr in [0.001]:

            print(f"Testing: units={units}")

            model = create_gru(units, dropout, lr)

            history = model.fit(
                X_small, y_small,
                epochs=1,
                batch_size=128,
                validation_split=0.2,
                verbose=0
            )

            val_acc = max(history.history['val_accuracy'])

            if val_acc > best_gru_acc:
                best_gru_acc = val_acc
                best_gru_params = {
                    'units': units,
                    'dropout': dropout,
                    'lr': lr
                }

print("Best GRU Params:", best_gru_params)

gru_model = create_gru(**best_gru_params)
gru_model.fit(X_train, y_train, epochs=5, batch_size=64)

y_pred_lstm = (lstm_model.predict(X_test) > 0.3).astype(int)
lstm_acc = accuracy_score(y_test, y_pred_lstm)


y_pred_gru = (gru_model.predict(X_test) > 0.3).astype(int)
gru_acc = accuracy_score(y_test, y_pred_gru)

print("\nFinal Results")
print("LSTM Accuracy:", lstm_acc)
print("GRU Accuracy:", gru_acc)

def predict_fraud(model, recent_transactions):
    recent_transactions = np.array(recent_transactions)
    recent_transactions = recent_transactions.reshape(1, X.shape[1], X.shape[2])

    prob = model.predict(recent_transactions)[0][0]

    if prob > 0.3:
        return "FRAUD", prob
    else:
        return "LEGIT", prob